"""
updater.py
Background self-update mechanism.

Every CHECK_INTERVAL_SEC the agent fetches an update manifest from the private
GitHub repo (authenticated with the read-only token captured at install time).
If the manifest's version differs from the running AGENT_VERSION, it downloads
the changed source files into the installed agent tree and restarts itself.

Config is written by install.py to:
    ~/TestingToolkit/update.json   ->  {"manifest_url": "...", "token": "..."}

The manifest (agent-update.json, generated by scripts/build-agent-update-manifest.mjs)
looks like:
    {
      "version": "1.0.1",
      "files": [
        {"path": "agent/server.py", "url": "<github contents api url>", "hash": "<sha256>"},
        ...
      ]
    }
`path` is relative to the installed `src/` directory.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any

import httpx

from agent.version import AGENT_VERSION

CHECK_INTERVAL_SEC: int = 60
MANIFEST_URL: str = ""
_stop_event = threading.Event()


def install_dir() -> Path:
    """Directory the agent is installed into (holds update.json, pid, etc.)."""
    return Path(
        os.environ.get("TT_INSTALL_DIR", Path.home() / "TestingToolkitWeb")
    ).expanduser()


def _config_path() -> Path:
    return install_dir() / "update.json"


def _load_config() -> dict[str, Any]:
    try:
        return json.loads(_config_path().read_text())
    except Exception:
        return {}


def resolve_manifest_url() -> str:
    """Where to poll for updates. Prefers the install-time config file."""
    cfg = _load_config()
    return cfg.get("manifest_url", "") or os.environ.get("AGENT_MANIFEST_URL", "")


def _auth_headers() -> dict[str, str]:
    """GitHub auth headers using the token persisted at install time."""
    cfg = _load_config()
    token = cfg.get("token", "") or os.environ.get("TT_UPDATE_TOKEN", "")
    headers = {"User-Agent": "TestingToolkit-Agent"}
    if token:
        headers["Authorization"] = "Bearer " + token
        # raw media type makes the contents API return file bytes directly.
        headers["Accept"] = "application/vnd.github.raw"
    return headers


def start_update_loop(manifest_url: str) -> None:
    """Start the background update checker thread."""
    global MANIFEST_URL
    MANIFEST_URL = manifest_url
    t = threading.Thread(target=_update_loop, daemon=True, name="updater")
    t.start()


def _update_loop() -> None:
    while not _stop_event.is_set():
        try:
            _check_and_apply()
        except Exception:
            pass
        _stop_event.wait(CHECK_INTERVAL_SEC)


def _fetch_manifest() -> dict[str, Any] | None:
    """Fetch + parse the update manifest, or None if not configured/reachable."""
    url = MANIFEST_URL or resolve_manifest_url()
    if not url:
        return None
    try:
        resp = httpx.get(url, headers=_auth_headers(), timeout=10,
                         follow_redirects=True)
        if resp.status_code != 200:
            return None
        return resp.json()
    except Exception:
        return None


def check_for_update() -> dict[str, Any]:
    """Non-destructive: report current vs. available version. Safe to call
    on demand from the UI; never downloads or restarts anything."""
    configured = bool(MANIFEST_URL or resolve_manifest_url())
    manifest = _fetch_manifest()
    latest = manifest.get("version", "") if manifest else ""
    return {
        "current": AGENT_VERSION,
        "latest": latest or None,
        "update_available": bool(latest and latest != AGENT_VERSION),
        "configured": configured,
        "reachable": manifest is not None,
        "install_dir": str(install_dir()),
    }


def _apply_manifest(manifest: dict[str, Any], *, defer_restart: bool = False) -> str:
    """Download, verify and install the files in ``manifest``.

    Returns "up_to_date", "applied" or "failed". When ``defer_restart`` is
    True the restart is scheduled ~1s out so an HTTP caller can get a response
    back before the process is replaced.
    """
    remote_version = manifest.get("version", "")
    if not remote_version or remote_version == AGENT_VERSION:
        return "up_to_date"

    files = manifest.get("files", [])
    if not files:
        return "up_to_date"

    headers = _auth_headers()

    # Installed layout: this file is <install>/agent/src/agent/updater.py
    # so src_root = <install>/agent/src and a manifest path "agent/server.py"
    # maps to <install>/agent/src/agent/server.py.
    src_root = Path(__file__).resolve().parent.parent

    staged: list[tuple[Path, bytes]] = []
    for file_info in files:
        rel_path = file_info.get("path", "")
        url = file_info.get("url", "")
        expected_hash = file_info.get("hash", "")
        if not rel_path or not url:
            continue
        try:
            r = httpx.get(url, headers=headers, timeout=30,
                          follow_redirects=True)
            if r.status_code != 200:
                return "failed"  # abort the whole update; try again next cycle
            content = r.content
            if expected_hash and hashlib.sha256(content).hexdigest() != expected_hash:
                return "failed"  # corrupt/mismatched -> do not apply partial
            staged.append((src_root / rel_path, content))
        except Exception:
            return "failed"

    # Install any new dependencies (extra wheels) BEFORE swapping in source
    # that imports them. If this fails we abort so we never restart into code
    # whose imports cannot resolve (which would crash-loop the agent).
    if not _install_extra_wheels(manifest.get("extraWheels") or [], headers):
        return "failed"

    # All files fetched and verified -> apply atomically-ish, then restart.
    for dest, content in staged:
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(content)
        except Exception:
            return "failed"

    if defer_restart:
        threading.Timer(1.0, _restart).start()
    else:
        _restart()
    return "applied"


def apply_update_now() -> dict[str, Any]:
    """On-demand update triggered from the UI. Downloads + applies the latest
    manifest and (if anything changed) schedules a restart so the new code
    takes effect. Returns a status dict for the caller to surface."""
    if not (MANIFEST_URL or resolve_manifest_url()):
        return {
            "applied": False, "status": "not_configured",
            "current": AGENT_VERSION, "latest": None, "restarting": False,
            "detail": "Automatic updates are not configured for this install.",
        }
    manifest = _fetch_manifest()
    if not manifest:
        return {
            "applied": False, "status": "unreachable",
            "current": AGENT_VERSION, "latest": None, "restarting": False,
            "detail": "Could not reach the update server.",
        }
    status = _apply_manifest(manifest, defer_restart=True)
    return {
        "applied": status == "applied",
        "status": status,
        "current": AGENT_VERSION,
        "latest": manifest.get("version", "") or None,
        "restarting": status == "applied",
    }


def _check_and_apply() -> None:
    manifest = _fetch_manifest()
    if not manifest:
        return
    _apply_manifest(manifest)


def _install_extra_wheels(wheels: list[dict[str, Any]], headers: dict[str, str]) -> bool:
    """Download and pip-install wheels added after the original bundle.

    Returns True on success (or when there is nothing to do). Wheels already
    importable are skipped, so this is a cheap no-op on the common path.
    """
    if not wheels:
        return True

    import importlib.util
    import tempfile

    # Map wheel -> import module name for a quick "already installed?" check.
    known_modules = {"python_multipart": "multipart", "python-multipart": "multipart"}

    to_install: list[dict[str, Any]] = []
    for w in wheels:
        name = w.get("name", "")
        dist = name.split("-", 1)[0] if name else ""
        mod = known_modules.get(dist, dist.replace("-", "_"))
        try:
            if mod and importlib.util.find_spec(mod) is not None:
                continue  # already present in the venv
        except Exception:
            pass
        to_install.append(w)

    if not to_install:
        return True

    tmpdir = Path(tempfile.mkdtemp(prefix="tt-wheels-"))
    paths: list[Path] = []
    for w in to_install:
        url = w.get("url", "")
        name = w.get("name", "")
        if not url or not name:
            continue
        try:
            r = httpx.get(url, headers=headers, timeout=60, follow_redirects=True)
            if r.status_code != 200:
                return False
            dest = tmpdir / name
            dest.write_bytes(r.content)
            paths.append(dest)
        except Exception:
            return False

    if not paths:
        return True

    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--no-index",
             "--no-deps", "--disable-pip-version-check", *map(str, paths)],
            check=True, capture_output=True, text=True, timeout=180,
        )
    except Exception:
        return False
    return True


def _restart() -> None:
    """Restart the agent process so the new code takes effect."""
    python = sys.executable
    try:
        if sys.platform == "win32":
            # Prefer pythonw.exe + CREATE_NO_WINDOW so the restarted agent has
            # no console window (matches the headless login task).
            pyw = Path(python).with_name("pythonw.exe")
            run_python = str(pyw) if pyw.exists() else python
            CREATE_NO_WINDOW = 0x08000000
            subprocess.Popen(
                [run_python, "-m", "agent"],
                creationflags=subprocess.CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW,
            )
            os._exit(0)
        else:
            os.execv(python, [python, "-m", "agent"])
    except Exception:
        pass


def stop() -> None:
    _stop_event.set()
